name: Add Jira Tickets to PR Description

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository with full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history to access both branches

      # Step 2: Extract Jira tickets from commit messages
      - name: Parse Jira ticket numbers from new commits
        id: extract-tickets
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}

          # Fetch all branches
          git fetch --all

          # Get new commits between base and head branches
          TICKETS=$(git log ${BASE_BRANCH}..${HEAD_BRANCH} --pretty=format:"%s" | grep -oE 'XYZ-[0-9]+' | sort -u | tr '\n' ' ')

          if [ -z "$TICKETS" ]; then
            echo "No Jira tickets found."
            echo "::set-output name=tickets::"
          else
            echo "Tickets found: $TICKETS"
            echo "::set-output name=tickets::$TICKETS"
          fi

      # Step 3: Add Jira ticket links to the PR description
      - uses: actions/github-script@v6
        with:
          script: |
            const tickets = '${{ steps.extract-tickets.outputs.tickets }}'.trim();

            if (tickets) {
              const ticketArray = tickets.split(" ");
              let ticketLinks = ticketArray.map(ticket => `* [${ticket}](https://your-jira-domain.atlassian.net/browse/${ticket})`).join('\n');

              const { data: pullRequest } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });

              const updatedBody = `${pullRequest.body}\n\nThe following Jira tickets are referenced in this PR:\n${ticketLinks}`;

              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                body: updatedBody,
              });
            } else {
              console.log('No Jira tickets found to add to the PR description.');
            }
