name: Add Jira Tickets to PR Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository to access the commit history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      # Step 2: Extract Jira tickets from commit messages
      - name: Parse Jira ticket numbers from new commits
        id: extract-tickets
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH=${{ github.event.pull_request.head.ref }}

          # Get new commits between base and head branches
          TICKETS=$(git log ${BASE_BRANCH}..${HEAD_BRANCH} --pretty=format:"%s" | grep -o 'XYZ-[0-9]\+' | sort -u | tr '\n' ' ')
          # TICKETS=$(git log --pretty=format:"%s" | grep -o 'XYZ-[0-9]\+' | sort -u | tr '\n' ' ')

          echo $TICKETS

          if [ -z "$TICKETS" ]; then
            echo "No Jira tickets found."
          else
            echo "Tickets found: $TICKETS"
          fi

      # Step 3: Add a comment to the PR with Jira ticket links
      - uses: actions/github-script@v6
        with:
          script: |
            const tickets = `${{ steps.extract-tickets.outputs.tickets }}`.trim();

            let commentBody = "The following Jira tickets are referenced in this PR:";

            if (tickets) {
              const ticketArray = tickets.split(" ");
              ticketArray.forEach(ticket => {
                commentBody += `\n* [${ticket}](https://your-jira-domain.atlassian.net/browse/${ticket})`;
              });
            } else {
              commentBody = "No Jira tickets found in the commit messages.";
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });
